import type { Metadata } from "next";
import {
  DM_Serif_Display,
  DM_Serif_Text,
  Klee_One,
  DM_Sans,
} from "next/font/google";
import Header from "../components/layout/Header";
import "./globals.css";

const dmSerifDisplay = DM_Serif_Display({
  variable: "--font-dm-serif-display",
  subsets: ["latin"],
  weight: "400",
});

const dmSerifText = DM_Serif_Text({
  variable: "--font-dm-serif-text",
  subsets: ["latin"],
  weight: ["400"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400"],
});

const kleeOne = Klee_One({
  variable: "--font-klee-one",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body
        className={`${dmSerifDisplay.variable} ${dmSerifText.variable} ${kleeOne.variable} ${dmSans.variable} antialiased h-screen w-full`}
      >
        <Header />
        <main className="h-full py-8  pt-32">{children}</main>
        {/* <div
          className="fixed top-0 right-0 bottom-0 left-0 bg-[url('/image/papernoise.webp')] bg-repeat opacity-[.16] pointer-events-none"
          style={{
            backgroundSize: "400px 400px",
            zIndex: "var(--zIndex-noiseBg)",
          }}
        ></div> */}
        <div
          className="fixed top-0 right-0 bottom-0 left-0 bg-[url('/image/woodenboard.jpg')] pointer-events-none"
          style={{
            backgroundSize: "auto 100%",
            zIndex: "var(--zIndex-noiseBg)",
          }}
        ></div>
      </body>
    </html>
  );
}
